const website = [
    {
        name:'前端相关',
        children:[
            {
                name:'掘金',
                url:''
            },
            {
                name:'淘宝前端fed',
                url:'http://taobaofed.org/'
            },
            {
                name:'腾讯Alloyteam',
                url:'http://www.alloyteam.com/'
            },
            {
                name:'腾讯 isux',
                url:'https://isux.tencent.com/'
            },
            {
                name:'IMWEB',
                url:'http://imweb.io/'
            },
            {
                name:'百度 fex',
                url:'http://fex.baidu.com/'
            },
            {
                name:'百度 EFE',
                url:'http://efe.baidu.com/'
            },
            {
                name:'百度 FIS',
                url:'http://fis.baidu.com/'
            },
            {
                name:'去哪网开发',
                url:'http://ued.qunar.com/fekit/'
            },
            {
                name:'菜鸟教程',
                url:'http://www.runoob.com/'
            },
            {
                name:'张鑫旭',
                url:'https://www.zhangxinxu.com/'
            },
            {
                name:'阮一峰',
                url:'http://www.ruanyifeng.com/home.html'
            },
            {
                name:'大数据过往记忆',
                url:'https://www.iteblog.com/'
            },
            {
                name:'极客学院 wiki',
                url:'http://wiki.jikexueyuan.com/'
            },
            {
                name:'前端工程模块化',
                url:'http://fex.baidu.com/blog/2014/03/fis-module/'
            },
            {
                name:'html5tricks',
                url:'ttps://www.html5tricks.com/'
            },
            {
                name:'MDN',
                url:'https://developer.mozilla.org/zh-CN/'
            },
            {
                name:'github',
                url:'https://github.com/'
            },
            {
                name:'css88',
                url:'http://www.css88.com/'
            },
            {
                name:'w3cplus',
                url:'http://www.w3cplus.com/'
            },
            {
                name:'w3help',
                url:'http://www.w3help.org/zh-cn/kb/'
            },
            {
                name:'html5plus',
                url:'http://www.html5plus.org/doc/h5p.html'
            }

        ]
    },
    {
        name:'交互设计',
        children:[
            {
                name:'web 安全色',
                url:'http://www.bootcss.com/p/websafecolors/'
            },
            {
                name:'颜色',
                url:'https://sjolzy.cn/html/Nice_color.html'
            },
            {
                name:'sketch 中文网',
                url:'http://www.sketchcn.com/'
            },
            {
                name:'花瓣',
                url:'http://huaban.com/'
            },
            {
                name:'千图网',
                url:'http://www.58pic.com/'
            },

            {
                name:'懒人图库',
                url:'http://www.lanrentuku.com/'
            },
            {
                name:'17素材',
                url:'http://www.17sucai.com/'
            },
            {
                name:'literally canvas',
                url:'http://literallycanvas.com/'
            },
            {
                name:'创客贴',
                url:'https://www.chuangkit.com/designtools/designindex'
            },
            {
                name:'UI中国',
                url:'http://www.ui.cn/'
            },
            {
                name:'UI 设计导航',
                url:'http://hao.xueui.cn/wcat/xinshou'
            },{
                name:'fontello',
                url:'ttp://fontello.com/'
            },

        ]
    },
    {
        name:'教育相关',
        children:[
            {
                name:'研招网',
                url:'http://yz.chsi.com.cn/'
            },
            {
                name:'学信网',
                url:'http://www.chsi.com.cn/'
            }
        ]
    },
]